import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import clsx from "clsx";
import "./globals.css";
import Header from "@/component/Header";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(urbanist.className, "relative min-h-screen")}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
