// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_us: dynamic(() => import("./ContactUs")),
  content_index: dynamic(() => import("./Blog")),
  gallery_index: dynamic(() => import("./Search")),
  hero: dynamic(() => import("./HomePage")),
  image_block: dynamic(() => import("./ImageBlock")),
  products: dynamic(() => import("./ProductEmbed")),
  text_block: dynamic(() => import("./TextBlock")),
};
